name: Manual Check
on: [workflow_dispatch]
jobs:
  check_release:
    name: Check Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: getting notification data
        run: |
          curl -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.notification_check }}" \
          https://api.github.com/notifications -o data.json
      - name: parse notif
        id: parsed
        run: |
          echo "type=$(jq -r '.[].subject.type' data.json)" >> $GITHUB_OUTPUT
          echo "repo=$(jq -r '.[].repository.name' data.json)" >> $GITHUB_OUTPUT
          echo "
        #run: echo '::set-output name=type ::'$(jq -r '.[].subject.type' data.json)
