name: Manual Check
on: [workflow_dispatch]
jobs:
  check_release:
    name: Check Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: getting notification data
        run: |
          curl -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.notif_check }}" \
          https://api.github.com/repos/Bwu1999/Trigger_Test/notifications
